#!/bin/sh

set -e

DIR="${ARPON_DIR:-/etc/arpon}"
SARPI="${DIR}/arpon.sarpi"
IFACE="${ARPON_IFACE:-eth0}"

# If the directory exists, it has been mounted to provide a static cache
if [ -d "$DIR" ]; then
    MAC=$(cat /sys/class/net/${IFACE}/address)
    IP=$(ifconfig $IFACE | awk '/inet / {print $2}' | sed 's/addr://')

    if [ -z "$MAC" ] || [ -z "$IP" ]; then
        echo "ARPON: failed to gather system network information"
        exit 1
    fi
    
    # A newer version allows setting the configuration file.
    # The link is until this is availible
    echo "$IP    $MAC" >> $SARPI
    rm /etc/arpon.conf && ln -s $SARPI /etc/arpon.conf
    echo "ARPON: starting arpon in static mode"
    ARPON="arpon -d -i $IFACE -S"

# Otherwise use dynamic, which doesn't work quite as well
else
    echo "ARPON: starting arpon in dynamic mode"
    ARPON="arpon -d -i $IFACE -D"
fi

$ARPON

# If we are using a static cache, set a trigger to reboot arpon on cache edit
if [ -d "$DIR" ]; then
    LTIME=`stat -c %Y $SARPI`

    while true; do
       ATIME=`stat -c %Y $SARPI`

       if [ "$ATIME" != "$LTIME" ]
       then    
           LTIME=$ATIME
           if [ -r /var/run/arpon.pid ]; then
               kill `cat /var/run/arpon.pid`
           fi
           $ARPON
       fi
       sleep 1
    done &
fi

echo "ARPON: setup now running $@"
exec "$@"
