#!/usr/bin/env python3

from argparse import ArgumentParser
from redis import StrictRedis

if __name__ == "__main__":
    parser = ArgumentParser(description="Interface with the OpenVPN. Stores CN-address realations into a Redis DB")
    parser.add_argument('action', help="The action to be prefeormed for the given args. From set {add, update, delete}", choices=["add", "update", "delete"])
    parser.add_argument('addr', help="MAC address associated with the given common name")
    parser.add_argument('cn', help="The common name (CN) associated with the address", nargs='?') 

    args = parser.parse_args()

    redis = StrictRedis(host='redis', port=6379)

    resp = None
    if args.action == "add" or args.action == "update":
        if not args.cn:
            raise ValueError("CN is required for add/update")
        addr = redis.get(args.cn)
        if addr:
            redis.delete(addr)
        redis.set(args.cn, args.addr)
        redis.set(args.addr, args.cn)
    elif args.action == "delete":
        cn = redis.get(args.addr)
        if cn:
            redis.delete(cn)
        redis.delete(args.addr)
    else:
        raise ValueError("Unrecognized command: {}".format(args.action))

    print("Successful completed {} {} {}".format(args.action, args.addr, args.cn))
