#!/bin/bash

#################################
# Set up Traffic Control redirect
# Requires: iproute2
#################################

# Define the name of the TAP interface.
# for example tap="tap0".
tap="tap0"
vethlocal="vth0"
vethhost="vth${HOSTNAME:0:12}" # Needs to be unique on the docker host

# Create the veth pair and throw one end of the can and string to the host
ip link add $vethlocal type veth peer name "$vethhost"

# Make the basic tunnel device for OpenVPN to use
mkdir /dev/net/
mknod /dev/net/tun c 10 200

# Configure the tunnel device. Do not start the OpenVPN service
openvpn --mktun --dev "$tap"
ifconfig "$tap" 0.0.0.0 promisc up

ifconfig $vethlocal 0.0.0.0 promisc up
ip link set "$vethhost" netns host

# Use traffic control to redirect all ingress packets on tap0 to the veth port directed at the challenge network, and vice versa. 
# Allows the forwarding of traffic without inserting an L2 device
# Use stochatic fairness queue to (in theory) divy up connection time fairly between users (to avoid MAC flood DOSing the link)
tc qdisc add dev "$vethlocal" root sfq
tc qdisc add dev "$tap" handle ffff: ingress
tc filter add dev "$tap" parent ffff: u32 \
    match u32 0 0 \
    action mirred egress redirect dev "$vethlocal"

tc qdisc add dev "$tap" root sfq
tc qdisc add dev "$vethlocal" handle ffff: ingress
tc filter add dev "$vethlocal" parent ffff: u32 \
    match u32 0 0 \
    action mirred egress redirect dev "$tap"

# Place all needed env variables into a yaml file
# This is so the nobody user can access these
printf "\
redis_hostname: ${REDIS_HOSTNAME:-null}\n\
redis_db: ${REDIS_DB:-null}\n\
redis_port: ${REDIS_PORT:-null}\n\
redis_password: ${REDIS_PASSWORD:-null}\n\
hostname: ${HOSTNAME:-null}\n\
naum_vethhost: ${vethhost:-null}\n\
naum_files: ${NAUM_FILES:-null}\n\
naum_chal: ${NAUM_CHAL:-null}\n\
push_addr: ${PUSH_ADDR:-null}\n\
push_mask: ${PUSH_MASK:-null}\n\
" > env.yaml
chmod 644 env.yaml
chown nobody:nobody env.yaml

/scripts/naumachia/register_vpn.py

echo "naumachia-start complete: now running $*"
exec "$@"
