declare -x OVPN_AUTH="SHA256"
declare -x OVPN_CIPHER="AES-256-CBC"
declare -x OVPN_CLIENT_TO_CLIENT
declare -x OVPN_CN="ctf.cse.tamu.edu"
declare -x OVPN_COMP_LZO="1"
declare -x OVPN_DEFROUTE="0"
declare -x OVPN_DEVICE="tap"
declare -x OVPN_DNS="1"
declare -x OVPN_ENV="/etc/openvpn/ovpn_env.sh"
declare -x OVPN_FRAGMENT
declare -x OVPN_MTU
declare -x OVPN_NAT="0"
declare -x OVPN_OTP_AUTH
declare -x OVPN_PORT="1194"
declare -x OVPN_PROTO="udp"
declare -x OVPN_PUSH
declare -x OVPN_ROUTES
declare -x OVPN_SERVER="192.168.255.0/24"
declare -x OVPN_SERVER_URL="udp://ctf.cse.tamu.edu:1194"
declare -x OVPN_TLS_CIPHER=""
